// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBroxcgzCpLYxN9CBRaSHrDrs4wtqiXlSk',
    appId: '1:678771931205:web:9323f94902550a700ecb2c',
    messagingSenderId: '678771931205',
    projectId: 'sigin-and-sigup-414c8',
    authDomain: 'sigin-and-sigup-414c8.firebaseapp.com',
    storageBucket: 'sigin-and-sigup-414c8.firebasestorage.app',
    measurementId: 'G-2Q06NJJQ1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjo3dC4DwoO44lqQJ4VLYaSolFWXh7d20',
    appId: '1:678771931205:android:64f466d4411eb2280ecb2c',
    messagingSenderId: '678771931205',
    projectId: 'sigin-and-sigup-414c8',
    storageBucket: 'sigin-and-sigup-414c8.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjwrMisKypAftXY_HFLzKvxclJPOb03Pg',
    appId: '1:678771931205:ios:cec8a5425090ec040ecb2c',
    messagingSenderId: '678771931205',
    projectId: 'sigin-and-sigup-414c8',
    storageBucket: 'sigin-and-sigup-414c8.firebasestorage.app',
    iosBundleId: 'com.example.loginAndSigin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjwrMisKypAftXY_HFLzKvxclJPOb03Pg',
    appId: '1:678771931205:ios:cec8a5425090ec040ecb2c',
    messagingSenderId: '678771931205',
    projectId: 'sigin-and-sigup-414c8',
    storageBucket: 'sigin-and-sigup-414c8.firebasestorage.app',
    iosBundleId: 'com.example.loginAndSigin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBroxcgzCpLYxN9CBRaSHrDrs4wtqiXlSk',
    appId: '1:678771931205:web:75fd5ef1af9771ea0ecb2c',
    messagingSenderId: '678771931205',
    projectId: 'sigin-and-sigup-414c8',
    authDomain: 'sigin-and-sigup-414c8.firebaseapp.com',
    storageBucket: 'sigin-and-sigup-414c8.firebasestorage.app',
    measurementId: 'G-SN1X05Q7V0',
  );
}
